/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Arrow: typeof import('./src/components/icons/Arrow.vue')['default']
    ArrowLink: typeof import('./src/components/ArrowLink.vue')['default']
    ContentTitle: typeof import('./src/components/ContentTitle.vue')['default']
    GithubIcon: typeof import('./src/components/icons/GithubIcon.vue')['default']
    IconBtn: typeof import('./src/components/IconBtn.vue')['default']
    LinkedIn: typeof import('./src/components/icons/LinkedIn.vue')['default']
    LinkIcon: typeof import('./src/components/icons/LinkIcon.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectLayout: typeof import('./src/components/layouts/ProjectLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableOfContent: typeof import('./src/components/TableOfContent.vue')['default']
  }
}
